services:
  name: docker:24.0.5-dind
  command: ["--insecure-registry=192.168.1.121:6000","--registry-mirror=http://192.168.1.121:6000" ]
  alias: docker
stages:
  - build

build:
  stage: build
  timeout: 3 hours 30 minutes
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  only:
    - main
  script:
    - apk add --no-cache git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
