version: '2'
services:
    classrum:
      restart: always
      build: .
      security_opt:
        - systempaths=unconfined
      devices:
        - /dev/dri:/dev/dri
      volumes:
        - jiebacache:/tmp/
      network:
        - dokploy-network

volumes:
  jiebacache:
